global:
  version: 1.0
  username: ''
  out_dir: output
  jobs_log_dir: output/logs/jobs
  bind: []
  conda_env: mamma
  start_frame: 60
  end_frame: 90
ma_cap:
  engine: conda
  enabled: true
  dependencies: []
  script: run_ma_cap.py
  repo_path: capture
  flags: []
ma_masks:
  engine: conda
  enabled: true
  dependencies:
  - ma_cap
  script: run_ma_masks.py
  repo_path: segmentation
  flags:
  - --sam_version sam2
  undistort: false
ma_2d:
  engine: conda
  enabled: true
  dependencies:
  - ma_masks
  script: run_ma_2d.py
  repo_path: landmarks
  config_path: configs/train/models_2d/config_mammanet_mask_512.yaml
  weights: data/weights/ma_2d/mamma_mask_full_cvpr.ckpt
  flags: []
  undistort: false
ma_3d:
  engine: conda
  enabled: false
  dependencies:
  - ma_2d
  script: run_ma_3d.py
  repo_path: optimization
  config_file: config_files/contact_configs/config_real_gmf_small_vals_detr_exp_no_vtemplate.yaml
  flags: []
ma_vis:
  engine: conda
  enabled: false
  dependencies:
  - ma_2d
  - ma_3d
  script: run_ma_vis.py
  repo_path: visualization
  flags: []
  undistort: false
